---
- name: Create Logstash inputs.
  template:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - ../templates/inputs/*.j2
  notify: restart logstash

- name: Create Logstash filters.
  copy:
    src: "files/filters/"
    dest: "/etc/logstash/conf.d/"
    owner: root
    group: root
    mode: 0644
  notify: restart logstash

- name: Find Logstah GeoLite2-City DB
  find:
    paths: "/usr/share/logstash/vendor/bundle/jruby/"
    file_type: "file"
    patterns: "GeoLite2-City.mmdb"
    recurse: yes
  register: find_GeoLite2_City_location

- name: Find Logstah GeoLite2-ASN DB
  find:
    paths: "/usr/share/logstash/vendor/bundle/jruby/"
    file_type: "file"
    patterns: "GeoLite2-ASN.mmdb"
    recurse: yes
  register: find_GeoLite2_ASN_location

- name: Set fact for GeoIP DB locations
  set_fact:
    GeoLite2_City_location: "{{ find_GeoLite2_City_location.files[0].path }}"
    GeoLite2_ASN_location: "{{ find_GeoLite2_ASN_location.files[0].path }}"

- name: Create GeoIP filter.
  template:
    src:  filters/198_geoipenrich.filter.conf.j2
    dest: /etc/logstash/conf.d/198_geoipenrich.filter.conf
    owner: root
    group: root
    mode: 0644
  notify: restart logstash

- name: Create Logstash output.
  template:
    src:  outputs/tpot.output.conf.j2
    dest: /etc/logstash/conf.d/{{ item.id }}_{{ item.name }}.output.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{ index_list }}"
  notify: restart logstash

- name: Create ES index template.
  copy:
    src: es-templates/tpot_es_template.json
    dest: /etc/logstash/tpot_es_template.json
    owner: root
    group: root
    mode: 0644
  notify: restart logstash

- name: Make listbot directory.
  file:
    path: /etc/listbot
    state: directory

- name: Download listbot data.
  get_url:
    url: "{{ item }}"
    dest: /tmp
  with_items:
    - https://listbot.sicherheitstacho.eu/cve.yaml.bz2
    - https://listbot.sicherheitstacho.eu/iprep.yaml.bz2
  changed_when: false

- name: Extract listbot data.
  shell: "bunzip2 -f *.bz2"
  args:
    chdir: /tmp
  changed_when: false

- name: Copy listbot data.
  copy:
    src: /tmp/{{ item }}
    dest: /etc/listbot
    remote_src: yes
  with_items:
    - cve.yaml
    - iprep.yaml
  notify: restart logstash

- name: Cleanup listbot data in /tmp.
  file:
    path: /tmp/{{ item }}
    state: absent
  with_items:
    - cve.yaml
    - iprep.yaml
  changed_when: false
