---
- name: Create Logstash inputs.
  template:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - ../templates/inputs/*.j2
  notify: restart logstash

- name: Create Logstash filters.
  copy:
    src: "files/filters/"
    dest: "/etc/logstash/conf.d/"
    owner: root
    group: root
    mode: 0644
  notify: restart logstash

- name: Create Logstash output.
  template:
    src:  "{{ item }}"
    dest: /etc/logstash/conf.d/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - ../templates/outputs/*.j2
  notify: restart logstash
  
- name: Git clone dtag-dev-sec/listbot repo
  git:
    repo: https://github.com/dtag-dev-sec/listbot
    dest: /etc/listbot
    depth: 1
  notify: restart logstash

- name: Download updated Geo ASN
  get_url:
    url: http://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz
    dest: /tmp/GeoLite2-ASN.tar.gz

- name: Extract Geo ASN
  unarchive:
    src: /tmp/GeoLite2-ASN.tar.gz
    dest: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-geoip-6.0.3-java/vendor/
    remote_src: yes
    extra_opts: [ --strip-components=1 ]
  notify: restart logstash
